import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "../components/ui/sonner"
import NextTopLoader from 'nextjs-toploader';
 
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader />
         <Toaster richColors  position="top-center" />
        {children}
      </body>
    </html>
  );
}
